using Godot;
using System;

namespace Features.NonogramGridCreation.BarGeneration;

public abstract partial class BarControl : Control
{
    [ExportCategory("Notch Colors")]
    [Export] public Color NotchColor { get; set; } = Colors.MidnightBlue;
    [Export] public Color AltNotchColor { get; set; } = Colors.MidnightBlue;
    [Export] public Color SelectedNotchColor { get; set; } = Colors.MidnightBlue;

    [ExportCategory("Font Colors")]
    [Export] public Color MainFontColor { get; set; } = Colors.PaleGreen;
    [Export] public Color AltFontColor1 { get; set; } = Colors.Orange;
    [Export] public Color AltFontColor2 { get; set; } = Colors.OrangeRed;

    [ExportCategory("Fonts")]
    [Export] public FontVariation AltFont { get; set; }

    protected float notchThickness = 30; // how thick notches are
    protected int notchCount;            // how many notches in a bar. Coincides with cellCount

    protected R_BarHint barHint;
    protected int largestNumberAmount;
    protected float calcNotchHeight;

    protected float cellSize;

    protected int fontSize;                     // size of numbers
    protected float fontSizeModifier = .8f;     // forcing font size smaller depending on grid size

    protected GridCreation gridCreation;

    public override void _Ready()
    {
        gridCreation = GridCreation.Instance;
        cellSize = gridCreation.cellSize;
    }

    // TODO: iterate through number hints generated by NonogramPuzzleManager.
    //          Use code for Godot rulers

    /// <summary>
    /// Draws bars of number hints
    /// </summary>
    /// <param name="interval">distance between bars. Cell size</param>
    /// <param name="ratio">Scale of grid viewport</param>
    /// <param name="steps">how many notches in a bar. notch count</param>
    /// <param name="startPos">Starting position of the notches</param>
    protected abstract void DrawBarNumbers(float interval, float ratio, int steps, float startPos);

    /// <summary>
    /// Draws bar background of number hints
    /// </summary>
    /// <param name="interval">distance between bars. Cell size</param>
    /// <param name="ratio">Scale of grid viewport</param>
    /// <param name="steps">how many notches in a bar. notch count</param>
    /// <param name="startPos">Starting position of the notches</param>
    protected abstract void DrawBarBackgrounds(float interval, float ratio, float steps, float startPos);


}
