using Common;
using Godot;
using Godot.Collections;
using System;

namespace Features.NonogramGridCreation.BarGeneration;

[Tool]
public abstract partial class BarControl : Control
{
    [ExportCategory("Notch Colors")]
    [Export] public Color NotchColor { get; set; } = Colors.MidnightBlue;
    [Export] public Color AltNotchColor { get; set; } = Colors.MidnightBlue;
    [Export] public Color SelectedNotchColor { get; set; } = Colors.MidnightBlue;
    [Export] public Color BGColor { get; set; } = Colors.SeaGreen;

    [ExportCategory("Font Colors")]
    [Export] public Color MainFontColor { get; set; } = Colors.PaleGreen;
    [Export] public Color AltFontColor1 { get; set; } = Colors.Orange;
    [Export] public Color AltFontColor2 { get; set; } = Colors.OrangeRed;

    [ExportCategory("Fonts")]
    [Export] public FontVariation AltFont { get; set; }

    protected float notchThickness = 30; // how thick notches are
    protected int notchCount;            // how many notches in a bar. Coincides with cellCount

    protected Array<RC_NotchHint> barHint;
    protected int largestNumberAmount;

    protected float cellSize;

    protected int fontSize = 40;                     // size of numbers
    protected float fontSizeModifier = .8f;     // forcing font size smaller than cell size

    protected GridCreation gridCreation;

    public async override void _Draw()
    {
        if (GridCreation.Instance == null || NonogramPuzzleManager.Instance == null)
            return;

        cellSize = GridCreation.Instance.cellSize;

        notchCount = GetNotchCount();
        barHint = GetNotchHints();

        if (cellSize <= 0)
        {
            GameLogger.Warning($"{Name}: Cell size not set");
            return;
        }
        if (notchCount <= 0)
        {
            GameLogger.Warning($"{Name}: Notch count not set");
            return;
        }

        Transform2D toCanvas = GridCreation.Instance.GetViewportTransform();
        float startPos = GetStartingPos(toCanvas);

        // doesn't matter which part of scale, since will always be uniform scale changes
        float ratio = toCanvas.Scale.Y;

        fontSizeModifier = BarSizeControl.fontSizeModifier;

        fontSize = Mathf.RoundToInt(cellSize * fontSizeModifier);   // font size cannot be float
        if (fontSize < 1)
            // prevent 0/-1 check
            fontSize = 1;
        
        notchThickness = cellSize * (cellSize > 37 ? .9f : 1); // thickness is slightly less than cellSize

        DrawWholeBarBackground(startPos);

        DrawNotchBackgrounds(ratio, notchCount, startPos);
        DrawNotchNumbers(cellSize, ratio, notchCount, startPos);
    }

    // TODO: iterate through number hints generated by NonogramPuzzleManager.
    //          Use code for Godot rulers

    /// <summary>
    /// Draws bars of number hints
    /// </summary>
    /// <param name="interval">distance between bars. Cell size</param>
    /// <param name="_ratio">Scale of grid viewport</param>
    /// <param name="steps">how many notches in a bar. notch count</param>
    /// <param name="startPos">Starting position of the notches</param>
    protected abstract void DrawNotchNumbers(float interval, float _ratio, int steps, float startPos);

    /// <summary>
    /// Draws bar background of number hints
    /// </summary>
    /// <param name="_ratio">Scale of grid viewport</param>
    /// <param name="steps">how many notches in a bar. notch count</param>
    /// <param name="startPos">Starting position of the notches</param>
    protected abstract void DrawNotchBackgrounds(float _ratio, int steps, float startPos);

    /// <summary>
    /// Draws the background of the bar. For preventing bars from overlapping each other when zooming
    /// </summary>
    /// <param name="startPos"></param>
    protected abstract void DrawWholeBarBackground(float startPos);

    protected abstract float GetStartingPos(Transform2D viewport);

    protected string[] CreateStringArrayFromNotchHint(int index)
    {
        string[] numArray = new string[barHint[index].numberList.Count];

        for (int i = 0; i < barHint[index].numberList.Count; i++)
        {
            // gets every number in list as a string
            numArray[i] = barHint[index].numberList[i].ToString();
        }

        // ensures empty arrays have "0" string
        if (numArray.Length == 0)
            numArray = ["0"];

        return numArray;
    }
    /// <summary>
    /// Calculation for returning either black or whiteas the contrasting color of the bgColor
    /// </summary>
    /// <param name="_bgColor"></param>
    /// <returns></returns>
    protected static Color CheckLuminence(Color _bgColor)
    {
        Color newColor;
        float newR = .2126f * _bgColor.R;
        float newG = .7152f * _bgColor.G;
        float newB = .0722f * _bgColor.B;

        float luminence = newB + newG + newR;
        if (luminence > Mathf.Sqrt(1.05f * .05f) - .05f)
            newColor = Colors.Black;
        else
            newColor = Colors.White;

        return newColor;
    }
    protected abstract int GetNotchCount();

    protected abstract Array<RC_NotchHint> GetNotchHints();

    public override void _EnterTree()
    {
        GridCreation.OnGridFinishedInitializing += QueueRedraw;
    }

    public override void _ExitTree()
    {
        GridCreation.OnGridFinishedInitializing -= QueueRedraw;
    }
}
