using Common;
using Godot;
using Godot.Collections;
using System;

namespace Features.NonogramGridCreation.BarGeneration;

[Tool]
public abstract partial class BarControl : Control
{
    [ExportCategory("Notch Colors")]
    [Export] public Color NotchColor { get; set; } = Colors.MidnightBlue;
    [Export] public Color AltNotchColor { get; set; } = Colors.MidnightBlue;
    [Export] public Color SelectedNotchColor { get; set; } = Colors.MidnightBlue;

    [ExportCategory("Font Colors")]
    [Export] public Color MainFontColor { get; set; } = Colors.PaleGreen;
    [Export] public Color AltFontColor1 { get; set; } = Colors.Orange;
    [Export] public Color AltFontColor2 { get; set; } = Colors.OrangeRed;

    [ExportCategory("Fonts")]
    [Export] public FontVariation AltFont { get; set; }

    protected float notchThickness = 30; // how thick notches are
    protected int notchCount;            // how many notches in a bar. Coincides with cellCount

    protected Array<R_BarHint> barHints;
    protected int largestNumberAmount;
    protected float calcNotchHeight;

    protected float cellSize;

    protected int fontSize = 40;                     // size of numbers
    protected float fontSizeModifier = .8f;     // forcing font size smaller than cell size

    protected GridCreation gridCreation;

    public async override void _Draw()
    {
        if (GridCreation.Instance == null || NonogramPuzzleManager.Instance == null)
            return;

        cellSize = GridCreation.Instance.cellSize;

        notchCount = NonogramPuzzleManager.CellCount.X;
        barHints = NonogramPuzzleManager.Instance.h_hints;

        if (cellSize <= 0)
        {
            GameLogger.Warning($"{Name}: Cell size not set");
            return;
        }
        if (notchCount <= 0)
        {
            GameLogger.Warning($"{Name}: Notch count not set");
            return;
        }

        Transform2D toCanvas = GridCreation.Instance.GetViewportTransform();
        float startPos = GetStartingPos(toCanvas);

        // doesn't matter which scale, since will always be uniform scale changes
        float ratio = toCanvas.Scale.Y;

        calcNotchHeight = 0;
        fontSize = Mathf.RoundToInt(cellSize * fontSizeModifier);
        if (fontSize < 1)
            // prevent 0/-1 check
            fontSize = 1;

        notchThickness = cellSize * .9f; // thickness is slightly less than cellSize

        DrawBarBackgrounds(cellSize, ratio, notchCount, startPos);
        DrawBarNumbers(cellSize, ratio, notchCount, startPos);
    }

    // TODO: iterate through number hints generated by NonogramPuzzleManager.
    //          Use code for Godot rulers

    /// <summary>
    /// Draws bars of number hints
    /// </summary>
    /// <param name="interval">distance between bars. Cell size</param>
    /// <param name="ratio">Scale of grid viewport</param>
    /// <param name="steps">how many notches in a bar. notch count</param>
    /// <param name="startPos">Starting position of the notches</param>
    protected abstract void DrawBarNumbers(float interval, float _ratio, int steps, float startPos);

    /// <summary>
    /// Draws bar background of number hints
    /// </summary>
    /// <param name="interval">distance between bars. Cell size</param>
    /// <param name="ratio">Scale of grid viewport</param>
    /// <param name="steps">how many notches in a bar. notch count</param>
    /// <param name="startPos">Starting position of the notches</param>
    protected abstract void DrawBarBackgrounds(float interval, float _ratio, int steps, float startPos);

    protected abstract float GetStartingPos(Transform2D viewport);

    private string CreateStringFromBarHint(int index)
    {
        string newString = "";
        //GD.Print(barHints[index].numberList);

        for (int i = 0; i < barHints[index].numberList.Count; i++)
        {
            newString += barHints[index].numberList[i].ToString();
            // add space between numbers for separation purpases
            if (i != barHints[index].numberList.Count - 1)
                newString += " ";
        }
        return newString;
    }

    protected string[] CreateStringArrayFromBarHint(int index)
    {
        // Get number list based on current notch
        string numString = CreateStringFromBarHint(index);
        // Split new string into a string array for each number
        string[] spltString = numString.Split(" ");

        // ensures empty arrays have "0" string
        if (spltString.Length == 0)
            spltString = ["0"];

        return spltString;
    }

    protected Color CheckLuminence(Color _bgColor)
    {
        Color newColor;
        float newR = .2126f * _bgColor.R;
        float newG = .7152f * _bgColor.G;
        float newB = .0722f * _bgColor.B;

        float luminence = newB + newG + newR;
        if (luminence > Mathf.Sqrt(luminence))
            newColor = Colors.Black;
        else
            newColor = Colors.White;

        return newColor;
    }

    public override void _EnterTree()
    {
        GridCreation.OnGridFinishedInitializing += QueueRedraw;
    }

    public override void _ExitTree()
    {
        GridCreation.OnGridFinishedInitializing -= QueueRedraw;
    }
}
